services:
  # ----------------------------------------------------
  # BANCO DE DADOS (MySQL)
  # ----------------------------------------------------
  db:
    image: mysql:8.0
    container_name: templo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: templo
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql # Salva os dados para não perder quando desligar o PC

  # ----------------------------------------------------
  # API (NestJS)
  # ----------------------------------------------------
  api:
    build: # Constrói o Dockerfile
      context: ./templo-api
      dockerfile: dockerfile
    container_name: templo_api
    restart: always
    ports:
      - '3000:3000'
    environment:
      # O segredo aqui é o '@db:', pois o NestJS vai procurar o banco pelo nome do container!
      DATABASE_URL: mysql://root:root@db:3306/templodb
    depends_on:
      - db
    volumes:
      - ./templo-api:/usr/src/app
      - /usr/src/app/node_modules
    # Comando mágico: Roda as migrations antes de ligar a API
    command: sh -c "npx prisma migrate dev && npm run start:dev"

  # ----------------------------------------------------
  # FRONTEND (React + Vite)
  # ----------------------------------------------------
  frontend:
    build:
      context: ./templo-frontend
      dockerfile: dockerfile
    container_name: templo_frontend
    restart: always
    ports:
      - '5173:5173'
    volumes:
      - ./templo-frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      VITE_API_URL: "http://localhost:3000"
    depends_on:
      - api
    command: npm run dev -- --host

# Declaração do volume do banco de dados
volumes:
  mysql_data: